export const GET_ALL_TOURS_SUCCESS ='GET_ALL_TOURS_SUCCESS';
export const GET_ALL_TOURS_FAILED ='GET_ALL_TOURS_FAILED';
export const CREATE_TOURS_SUCCESS ='CREATE_TOURS_SUCCESS';
export const CREATE_TOURS_FAILED ='CREATE_TOURS_FAILED';